# Generated by Django 4.2.3 on 2023-07-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_pic', models.ImageField(default='blog.png', upload_to='blog_pictures/')),
            ],
            options={
                'verbose_name': 'Blogs',
            },
        ),
    ]
