# Generated by Django 4.2.3 on 2023-07-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signed_up_user',
            options={'verbose_name': 'Signed in Users in Checkout Site'},
        ),
    ]
